name: Test Website

on:
  pull_request:
    paths:
      - "website/*"
  push:
    paths:
      - "website/*"

jobs:
  website:
    name: Test website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.0.0
      - name: Use npm 7.5
        run: |
          npm install -g npm@7.5
      - name: Install dependencies
        working-directory: website
        run: |
          npm install
      - name: Build website
        working-directory: website
        run: |
          npm run build
